# SST recommends and supports PlaceholderAPI. You can install it for using thousands of placeholders.
# You have to install ProtocolLib for editing client-side max player and player count in server list.

# Check https://github.com/bilektugrul/SimpleServerTools/tree/master/src/main/resources/language for supported languages
language: en

custom-placeholders: # You can use these placeholders everywhere in SST files. (%prefix%, %warpprefix%, %spawnprefix%)
                     # These placeholders also supports PAPI. (%sst_custom_(placeholdername)%)
  prefix: '&8[&6SST&8]&r'
  warpprefix: '&8[&6Warps&8]&r'
  spawnprefix: '&8[&6Spawn&8]&r'
  tpaprefix: '&8[&6TPA&8]&r'
  broadcastprefix: '&8[&6Broadcast&8]'
  #name: value - you can create yours like this

main-command-perm-required: true # if true, players will need "sst.maincmd" permission to use "/sst" command.
auto-save-users: true
auto-save-interval: 30 # in minutes
date-format: 'dd/MM/yyyy hh:mm'

updates:
  notify: true
  notify-beta-versions: true

join-quit-messages:
  enabled: true
  first-join-message: '&9[+] &b&l%player% &7has joined or server for the first time..'
  join-message: '&9[+] &b&l%player% &7has joined.'
  quit-message: '&9[-] &b&l%player% &7has left.'

one-more-slot:
  enabled: true # Requires Protocollib

vanish:
  remove-vanished-players: true # Removes vanished players from client-side server list.
                                # requires ProtocolLib.
  messages-to-vanished-players: false # if true, players can send messages to vanished players. (/msg)

MOTD: # requires ProtocolLib.
  enabled: false
  value: |
    %prefix% &aYou should check this server!!!!
    %prefix% &aWe're so cool!

auto-respawn:
  enabled: true # removes respawn screen
  permission-required: false # sst.autorespawn

falling-into-void:
  teleport-spawn: false
  cancel-damage: false

titles: # Settings for title messages that are used in language files.
  fade-in: 0
  stay: 30
  fade-out: 0

warps:
  tab-complete: true # warp list will be sent to players when they click TAB. (they can not see warps with permissions if they don't have the permission.)
  teleport-time: 5 # in seconds
  staff-bypass-time: true
  cancel-when-move:
    settings:
      block-move: true # if true, players can not move while teleporting.
      cancel-teleport: false # if true, teleportation process will be cancelled when they moved.
    mode: EVERYONE
  cancel-damage:
    settings:
      block-damage: true
      cancel-teleport: false
    mode: EVERYONE
  block-commands:
    enabled: true
    mode: EVERYONE
  # Modes: EVERYONE, STAFF, EXCEPT_STAFF

tpa:
  allow-tpa-to-other-worlds: true
  accept-time: 10
  teleport-time: 5
  staff-bypass-time: true
  cancel-when-move:
    settings:
      block-move: true
      cancel-teleport: false
    mode: EVERYONE
  cancel-damage:
    settings:
      block-damage: true
      cancel-teleport: false
    mode: EVERYONE
  block-commands:
    enabled: true
    mode: EVERYONE
  # Modes: EVERYONE, STAFF, EXCEPT_STAFF

homes:
  default-max-home-amount: 3
  teleport-time: 5 # in seconds
  staff-bypass-time: true
  cancel-when-move:
    settings:
      block-move: true # if true, players can not move while teleporting.
      cancel-teleport: false # if true, teleportation process will be cancelled when they moved.
    mode: EVERYONE
  cancel-damage:
    settings:
      block-damage: true
      cancel-teleport: false
    mode: EVERYONE
  block-commands:
    enabled: true
    mode: EVERYONE
  # Modes: EVERYONE, STAFF, EXCEPT_STAFF

convert-enabled: false # disables /convert by default. set this to true if you want to use a converter.

disabled-commands:
  # examples
  #- HealCommand
  #- InvSeeCommand
  #- KickCommand
  #- <command class name>
  # all correct command class names can be found at
  # https://github.com/bilektugrul/SimpleServerTools/tree/master/src/main/java/io/github/bilektugrul/simpleservertools/commands

disable-death-messages: false
metrics-enabled: true # Sends some basic information about your server to bstats.org.
                      # Won't effect the performance but you can turn it off if you want. You must restart the server after changing the setting.